schema {
  query: Query
  mutation: Mutation
}

type AuthPayload {
  user: UserPayload
  token: String
  message: String
}

type ChatGroupPayload {
  id: String
  name: String
  members: [UserPayload!]!
  createdAt: DateTime!
}

type MessagePayload {
  id: String
  group: ChatGroupPayload
  sender: UserPayload
  text: String
  sentAt: DateTime!
}

type Mutation {
  login(username: String! password: String!): AuthPayload! @cost(weight: "10")
  register(username: String! password: String!): AuthPayload! @cost(weight: "10")
  createGroup(name: String!): ChatGroupPayload! @cost(weight: "10")
  addMember(groupId: String! userId: String!): ChatGroupPayload! @cost(weight: "10")
  removeMember(groupId: String! userId: String!): ChatGroupPayload! @cost(weight: "10")
  createMessage(groupId: String! text: String!): MessagePayload! @cost(weight: "10")
}

type Query {
  group(id: String!): ChatGroupPayload! @cost(weight: "10")
  searchGroupsByMember(userId: String!): [ChatGroupPayload!]! @cost(weight: "10")
  message(id: String!): MessagePayload! @cost(weight: "10")
  messages(groupId: String! skip: Int! limit: Int!): [MessagePayload!]! @cost(weight: "10")
  newerMessages(groupId: String! lastMessageId: String!): [MessagePayload!]! @cost(weight: "10")
  user(id: String!): User! @cost(weight: "10")
  searchUsers(nameSearch: String!): [User!]! @cost(weight: "10")
  me: User! @cost(weight: "10")
}

type User {
  id: String!
  username: String!
}

type UserPayload {
  id: String
  name: String
}

"The purpose of the `cost` directive is to define a `weight` for GraphQL types, fields, and arguments. Static analysis can use these weights when calculating the overall cost of a query or response."
directive @cost("The `weight` argument defines what value to add to the overall cost for every appearance, or possible appearance, of a type, field, argument, etc." weight: String!) on SCALAR | OBJECT | FIELD_DEFINITION | ARGUMENT_DEFINITION | ENUM | INPUT_FIELD_DEFINITION

"The `@specifiedBy` directive is used within the type system definition language to provide a URL for specifying the behavior of custom scalar definitions."
directive @specifiedBy("The specifiedBy URL points to a human-readable specification. This field will only read a result for scalar types." url: String!) on SCALAR

"The `DateTime` scalar represents an ISO-8601 compliant date time type."
scalar DateTime @specifiedBy(url: "https:\/\/www.graphql-scalars.com\/date-time")

"The `Upload` scalar type represents a file upload."
scalar Upload