//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoapChat.Api.MessageService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChatMessageResponse", Namespace="http://schemas.datacontract.org/2004/07/SoapChat.DbServer.Features")]
    public partial class ChatMessageResponse : object
    {
        
        private SoapChat.Api.MessageService.ChatGroupResponse GroupField;
        
        private string IdField;
        
        private SoapChat.Api.MessageService.UserResponse SenderField;
        
        private System.DateTime SentAtField;
        
        private string TextField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SoapChat.Api.MessageService.ChatGroupResponse Group
        {
            get
            {
                return this.GroupField;
            }
            set
            {
                this.GroupField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SoapChat.Api.MessageService.UserResponse Sender
        {
            get
            {
                return this.SenderField;
            }
            set
            {
                this.SenderField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime SentAt
        {
            get
            {
                return this.SentAtField;
            }
            set
            {
                this.SentAtField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Text
        {
            get
            {
                return this.TextField;
            }
            set
            {
                this.TextField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChatGroupResponse", Namespace="http://schemas.datacontract.org/2004/07/SoapChat.DbServer.Features")]
    public partial class ChatGroupResponse : object
    {
        
        private System.DateTime CreatedAtField;
        
        private string IdField;
        
        private SoapChat.Api.MessageService.UserResponse[] MembersField;
        
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedAt
        {
            get
            {
                return this.CreatedAtField;
            }
            set
            {
                this.CreatedAtField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SoapChat.Api.MessageService.UserResponse[] Members
        {
            get
            {
                return this.MembersField;
            }
            set
            {
                this.MembersField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserResponse", Namespace="http://schemas.datacontract.org/2004/07/SoapChat.DbServer.Features")]
    public partial class UserResponse : object
    {
        
        private string IdField;
        
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SoapChat.Api.MessageService.IMessageService")]
    public interface IMessageService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessageService/CreateMessage", ReplyAction="http://tempuri.org/IMessageService/CreateMessageResponse")]
        System.Threading.Tasks.Task<SoapChat.Api.MessageService.ChatMessageResponse> CreateMessageAsync(string groupId, string senderId, string text);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessageService/GetMessage", ReplyAction="http://tempuri.org/IMessageService/GetMessageResponse")]
        System.Threading.Tasks.Task<SoapChat.Api.MessageService.ChatMessageResponse> GetMessageAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessageService/GetMessages", ReplyAction="http://tempuri.org/IMessageService/GetMessagesResponse")]
        System.Threading.Tasks.Task<SoapChat.Api.MessageService.ChatMessageResponse[]> GetMessagesAsync(string groupId, int skip, int limit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessageService/GetNewerMessages", ReplyAction="http://tempuri.org/IMessageService/GetNewerMessagesResponse")]
        System.Threading.Tasks.Task<SoapChat.Api.MessageService.ChatMessageResponse[]> GetNewerMessagesAsync(string groupId, string lastMessageId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface IMessageServiceChannel : SoapChat.Api.MessageService.IMessageService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class MessageServiceClient : System.ServiceModel.ClientBase<SoapChat.Api.MessageService.IMessageService>, SoapChat.Api.MessageService.IMessageService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public MessageServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(MessageServiceClient.GetBindingForEndpoint(endpointConfiguration), MessageServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MessageServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(MessageServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MessageServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(MessageServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MessageServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<SoapChat.Api.MessageService.ChatMessageResponse> CreateMessageAsync(string groupId, string senderId, string text)
        {
            return base.Channel.CreateMessageAsync(groupId, senderId, text);
        }
        
        public System.Threading.Tasks.Task<SoapChat.Api.MessageService.ChatMessageResponse> GetMessageAsync(string id)
        {
            return base.Channel.GetMessageAsync(id);
        }
        
        public System.Threading.Tasks.Task<SoapChat.Api.MessageService.ChatMessageResponse[]> GetMessagesAsync(string groupId, int skip, int limit)
        {
            return base.Channel.GetMessagesAsync(groupId, skip, limit);
        }
        
        public System.Threading.Tasks.Task<SoapChat.Api.MessageService.ChatMessageResponse[]> GetNewerMessagesAsync(string groupId, string lastMessageId)
        {
            return base.Channel.GetNewerMessagesAsync(groupId, lastMessageId);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IMessageService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IMessageService1))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IMessageService))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:5044/Message.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IMessageService1))
            {
                return new System.ServiceModel.EndpointAddress("https://localhost:7179/Message.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IMessageService,
            
            BasicHttpBinding_IMessageService1,
        }
    }
}
