//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoapChat.Api.ChatGroupService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChatGroupResponse", Namespace="http://schemas.datacontract.org/2004/07/SoapChat.DbServer.Features")]
    public partial class ChatGroupResponse : object
    {
        
        private System.DateTime CreatedAtField;
        
        private string IdField;
        
        private SoapChat.Api.ChatGroupService.UserResponse[] MembersField;
        
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedAt
        {
            get
            {
                return this.CreatedAtField;
            }
            set
            {
                this.CreatedAtField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SoapChat.Api.ChatGroupService.UserResponse[] Members
        {
            get
            {
                return this.MembersField;
            }
            set
            {
                this.MembersField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserResponse", Namespace="http://schemas.datacontract.org/2004/07/SoapChat.DbServer.Features")]
    public partial class UserResponse : object
    {
        
        private string IdField;
        
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SoapChat.Api.ChatGroupService.IChatGroupService")]
    public interface IChatGroupService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChatGroupService/CreateGroup", ReplyAction="http://tempuri.org/IChatGroupService/CreateGroupResponse")]
        System.Threading.Tasks.Task<SoapChat.Api.ChatGroupService.ChatGroupResponse> CreateGroupAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChatGroupService/GetGroup", ReplyAction="http://tempuri.org/IChatGroupService/GetGroupResponse")]
        System.Threading.Tasks.Task<SoapChat.Api.ChatGroupService.ChatGroupResponse> GetGroupAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChatGroupService/SearchGroupsByMember", ReplyAction="http://tempuri.org/IChatGroupService/SearchGroupsByMemberResponse")]
        System.Threading.Tasks.Task<SoapChat.Api.ChatGroupService.ChatGroupResponse[]> SearchGroupsByMemberAsync(string userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChatGroupService/AddMember", ReplyAction="http://tempuri.org/IChatGroupService/AddMemberResponse")]
        System.Threading.Tasks.Task<SoapChat.Api.ChatGroupService.ChatGroupResponse> AddMemberAsync(string groupId, string userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChatGroupService/RemoveMember", ReplyAction="http://tempuri.org/IChatGroupService/RemoveMemberResponse")]
        System.Threading.Tasks.Task<SoapChat.Api.ChatGroupService.ChatGroupResponse> RemoveMemberAsync(string groupId, string userId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface IChatGroupServiceChannel : SoapChat.Api.ChatGroupService.IChatGroupService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class ChatGroupServiceClient : System.ServiceModel.ClientBase<SoapChat.Api.ChatGroupService.IChatGroupService>, SoapChat.Api.ChatGroupService.IChatGroupService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ChatGroupServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(ChatGroupServiceClient.GetBindingForEndpoint(endpointConfiguration), ChatGroupServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ChatGroupServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ChatGroupServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ChatGroupServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ChatGroupServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ChatGroupServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<SoapChat.Api.ChatGroupService.ChatGroupResponse> CreateGroupAsync(string name)
        {
            return base.Channel.CreateGroupAsync(name);
        }
        
        public System.Threading.Tasks.Task<SoapChat.Api.ChatGroupService.ChatGroupResponse> GetGroupAsync(string id)
        {
            return base.Channel.GetGroupAsync(id);
        }
        
        public System.Threading.Tasks.Task<SoapChat.Api.ChatGroupService.ChatGroupResponse[]> SearchGroupsByMemberAsync(string userId)
        {
            return base.Channel.SearchGroupsByMemberAsync(userId);
        }
        
        public System.Threading.Tasks.Task<SoapChat.Api.ChatGroupService.ChatGroupResponse> AddMemberAsync(string groupId, string userId)
        {
            return base.Channel.AddMemberAsync(groupId, userId);
        }
        
        public System.Threading.Tasks.Task<SoapChat.Api.ChatGroupService.ChatGroupResponse> RemoveMemberAsync(string groupId, string userId)
        {
            return base.Channel.RemoveMemberAsync(groupId, userId);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IChatGroupService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IChatGroupService1))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IChatGroupService))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:5044/ChatGroup.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IChatGroupService1))
            {
                return new System.ServiceModel.EndpointAddress("https://localhost:7179/ChatGroup.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IChatGroupService,
            
            BasicHttpBinding_IChatGroupService1,
        }
    }
}
